image: python:3.10

stages:
  - prod
pip_installs:
  stage: prod
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - pip install test_requirements.txt 
pytest:
  before_script:
    - cd $CI_PROJECT_DIR/tests/features/step_defs/prod
  stage: prod
  script:
    - pytest -v --url https://djangosite-uhgxj7hora-ew.a.run.app --cov-report term --cov=.
coverage:
  stage: prod
  script:
    - coverage xml
  artifacts:
    paths:
      - coverage.xml
  when: always